/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/DetailT-v1.glb --keepnames 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DetailT-v1.glb')
  return (
    <group {...props} dispose={null}>
      <group name="detail" position={[-9.876, 70.311, -4.071]} rotation={[1.571, 0, 0]}>
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.008']} />
        <mesh name="Text_1" geometry={nodes.Text_1.geometry} material={nodes.Text_1.material} />
        <mesh name="Text_2" geometry={nodes.Text_2.geometry} material={materials['Material.009']} />
        <mesh name="Text_3" geometry={nodes.Text_3.geometry} material={materials['Frame.002']} />
        <mesh name="Text_4" geometry={nodes.Text_4.geometry} material={materials['Project Three.002']} />
        <mesh name="Text_5" geometry={nodes.Text_5.geometry} material={materials['Material.010']} />
        <mesh name="Text_6" geometry={nodes.Text_6.geometry} material={materials['Project One.002']} />
        <mesh name="Text_7" geometry={nodes.Text_7.geometry} material={materials['Project Two.002']} />
        <mesh name="Text_8" geometry={nodes.Text_8.geometry} material={materials['Project Four.002']} />
        <mesh name="Text_9" geometry={nodes.Text_9.geometry} material={materials['Photo of Me.002']} />
        <mesh name="Text_10" geometry={nodes.Text_10.geometry} material={materials['Musser gap snow.002']} />
        <mesh name="Text_11" geometry={nodes.Text_11.geometry} material={materials['View.002']} />
        <mesh name="Text_12" geometry={nodes.Text_12.geometry} material={materials['David Vista.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/DetailT-v1.glb')
