/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/DetailT-v1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DetailT-v1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-9.876, 70.311, -4.071]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Text005.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Text005_1.geometry} material={nodes.Text005_1.material} />
        <mesh geometry={nodes.Text005_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Text005_3.geometry} material={materials.Frame} />
        <mesh geometry={nodes.Text005_4.geometry} material={materials['Project Three']} />
        <mesh geometry={nodes.Text005_5.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Text005_6.geometry} material={materials['Project One']} />
        <mesh geometry={nodes.Text005_7.geometry} material={materials['Project Two']} />
        <mesh geometry={nodes.Text005_8.geometry} material={materials['Project Four']} />
        <mesh geometry={nodes.Text005_9.geometry} material={materials['Photo of Me']} />
        <mesh geometry={nodes.Text005_10.geometry} material={materials['Musser gap snow']} />
        <mesh geometry={nodes.Text005_11.geometry} material={materials.View} />
        <mesh geometry={nodes.Text005_12.geometry} material={materials['David Vista']} />
      </group>
    </group>
  )
}

useGLTF.preload('/DetailT-v1.glb')
